services:
    api:
        image: node:18-alpine
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        ports: 
            - "3000:8080"
        command: sh -c "npm install && npm run dev"
        depends_on:
            - db
    
    db:
        image: mongo:8.0
        ports: 
            - "27017:27017"